// Can I make wordle?

// //Copy pasted from internet possible wordle answers as a string
// const possibleWords =
//   "ABACK ABASE ABATE ABBEY ABOVE ABYSS ACRID ACUTE ADMIT ADOBE ADOPT ADORE AGAIN AGAPE AGATE AGILE AGLOW AGONY AGREE AHEAD ALBUM ALIEN ALIKE ALLOW ALOFT ALONE ALOUD ALPHA ALTAR ALTER AMBER AMPLE ANGER ANGRY ANTIC AORTA APHID APPLE APPLY APRON APTLY ARBOR ARGUE AROMA ASIDE ASKEW ASSET ATOLL ATONE AUDIT AVAIL AVERT AWAKE AWFUL AXIOM BADGE BADLY BAGEL BAKER BALSA BANAL BASIC BATON BATTY BAYOU BEADY BEAST BEEFY BEGIN BEING BELCH BELIE BELLY BELOW BENCH BERTH BESET BIOME BIRTH BLACK BLAME BLAND BLEED BLOKE BLOWN BLUFF BLURB BLURT BLUSH BOOBY BOOST BOOZE BOOZY BORAX BOUGH BRAID BRAKE BRASH BRAVE BREAD BREAK BRIAR BRIBE BRINE BRING BRINK BRISK BROKE BROOM BUGGY CACAO CACHE CANNY CANOE CARAT CARGO CARRY CATCH CATER CAULK CEDAR CHAFE CHAMP CHANT CHARD CHARM CHEAT CHEEK CHEST CHIEF CHILL CHOKE CHORD CHUNK CHUTE CIDER CIGAR CINCH CIRCA CIVIC CLASS CLEAN CLERK CLICK CLING CLOCK CLOTH CLOWN CLUCK COAST COCOA COLON COMET COMMA CONDO CONIC CORNY COULD COUNT COVET COYLY CRAMP CRANE CRANK CRASS CRATE CRAVE CRAZE CRAZY CREAK CREDO CREPT CRIME CRIMP CROAK CROSS CRUMB CRUST CYNIC DANCE DANDY DEATH DEBUG DELTA DELVE DENIM DEPOT DEPTH DIGIT DITTO DODGE DONOR DOUBT DOWRY DOZEN DRAIN DREAM DRINK DRIVE DROLL DUCHY DUTCH DUVET DWARF DWELT EGRET EJECT ELDER ELOPE ELUDE EMAIL ENEMA ENJOY ENNUI EPOCH EPOXY EQUAL ERODE ERROR ESSAY ETHIC EVADE EVERY EXCEL EXIST EXTRA EXULT FARCE FAULT FAVOR FEAST FEIGN FERRY FEWER FIELD FIFTY FINER FIRST FISHY FIXER FJORD FLAIL FLAIR FLASK FLESH FLICK FLING FLIRT FLOAT FLOCK FLOOD FLOOR FLORA FLOSS FLOUT FLUFF FLUME FOCAL FOCUS FOGGY FORAY FORGE FORGO FORTH FOUND FOYER FRAME FRESH FROCK FRONT FROST FROTH FUNGI GAMER GAMMA GAUDY GAUZE GAWKY GECKO GHOUL GIANT GIRTH GLASS GLEAN GLOAT GLOOM GLORY GLOVE GLYPH GOLEM GONER GOOSE GORGE GOUGE GRADE GRATE GREAT GREET GRIEF GRIME GRIMY GRIPE GROIN GROUP GROUT GROVE GROWL GRUEL GUANO GUARD GUILD GULLY GUPPY HAIRY HAPPY HATCH HATER HAVOC HEADY HEATH HEIST HELIX HERON HINGE HOARD HOMER HORDE HORSE HOUND HOWDY HUMAN HUMID HUMOR HUMPH HUNKY HURRY HUTCH HYPER IGLOO IMPEL INANE INEPT INERT INFER INPUT INTER IONIC IRONY ISLET ITCHY IVORY JAUNT JAZZY JOKER JOUST JUDGE KARMA KAYAK KAZOO KEBAB KHAKI KIOSK KNEEL KNOCK KNOLL KOALA LABEL LABOR LAPEL LAPSE LARVA LATTE LAYER LEAFY LEAPT LEAVE LEDGE LEERY LEMON LIBEL LIGHT LILAC LINEN LIVER LOCUS LOFTY LOGIC LOOPY LOSER LOWLY LUNAR LUSTY LYING MADAM MAGIC MAIZE MAJOR MANLY MANOR MAPLE MARCH MARRY MARSH MASSE MATEY MAXIM MAYBE MEALY MEDAL MERIT METAL METRO MIDGE MIDST MIMIC MINCE MODEL MOIST MOLAR MONEY MONTH MOOSE MOTOR MOTTO MOULT MOUNT MOURN MOUSE MOVIE MUCKY MUMMY NAIVE NANNY NASTY NATAL NAVAL NEEDY NIGHT NINTH NYMPH OFFAL OLIVE ONSET OPERA OTHER OUGHT OUTDO OXIDE PANEL PANIC PAPER PARER PARRY PATTY PAUSE PEACH PERCH PERKY PHASE PHOTO PICKY PIETY PILOT PINEY PINKY PINTO PITHY PIXIE PLANK PLANT PLATE PLAZA PLEAT PLUCK PLUNK POINT POISE POKER POLKA POUND POWER PRICK PRIDE PRIME PRIMO PRINT PRIZE PROBE PROVE PROXY PULPY PURGE QUALM QUART QUERY QUIET QUIRK RADIO RAINY RAMEN RANCH RANGE RATIO REACT REBUS REBUT RECAP REGAL RENEW REPAY RETCH RETRO REVEL RHINO RHYME RIPER RIVAL ROBIN ROBOT ROGUE ROOMY ROUGE ROUND ROYAL RUDDY RUDER RUPEE RUSTY SAINT SALAD SALSA SAUTE SCALD SCARE SCARF SCOLD SCORN SCOUR SCOUT SCRAP SEDAN SEEDY SERVE SEVER SHAKE SHALL SHAME SHARD SHAWL SHINE SHIRE SHIRK SHORN SHOWN SHOWY SHRUB SHRUG SHYLY SIEGE SISSY SKILL SKIMP SKIRT SLATE SLEEK SLOSH SLOTH SLUMP SLUNG SMART SMASH SMEAR SMELT SMITE SNACK SNAFU SNARL SNEAK SNOUT SOGGY SOLAR SOLVE SONIC SOUND SOWER SPADE SPELL SPEND SPICY SPIEL SPIKE SPILL SPIRE SPOKE SPRAY SQUAD SQUAT STAFF STAGE STAID STAIR STALE STAND START STEAD STEED STEIN STICK STING STINK STOCK STOMP STOOL STORE STORY STOUT STOVE STRAP STUDY SUGAR SULKY SURER SURLY SWEAT SWEEP SWEET SWILL SWINE SWIRL SYRUP TACIT TANGY TAPER TAPIR TASTE TASTY TAUNT TEASE TEPID THEIR THEME THERE THIEF THIRD THORN THOSE THUMB THUMP THYME TIARA TIBIA TIGER TILDE TIPSY TODAY TORSO TOTEM TOUGH TOXIC TRACE TRAIN TRAIT TRASH TRAWL TREAT TREND TRIAD TRICE TRITE TROLL TROPE TROVE TRUSS TRYST TWANG TWEED TWICE TWINE ULCER ULTRA UNDER UNDUE UNFED UNFIT UNIFY UNITE UNLIT UNMET UNTIE UNZIP UPSET USAGE USHER USING USUAL USURP UTTER VAGUE VALET VALID VIGOR VIRAL VITAL VIVID VODKA VOICE VOTER VOUCH WACKY WALTZ WASTE WATCH WEARY WEDGE WHACK WHELP WHERE WHIFF WHINE WHOOP WINCE WOKEN WOOER WORLD WORRY WORSE WOVEN WRONG WROTE WRUNG YACHT YEARN YIELD YOUTH ZESTY";

// //Turn values into an array where each value is a word
// const possibleWordsArrayAlphabetical = possibleWords.split(" ");
// //console.log(possibleWordsArray);

//Copy pasted from interent function to return random element in array
//array[Math.floor(Math.random() * array.length)];
//
// const randomValue =
//   possibleWordsArray[Math.floor(Math.random() * possibleWordsArray.length)];
//
//console.log(randomValue);
//Couldn't implement... maybe in future.

//Copy pasted from the internet to randomize an array
//I did this to because array is alphabetical
//If low or hugh numbers are used you can somewhat predict how answer begins
function shuffle(array) {
  let currentIndex = array.length,
    randomIndex;

  // While there remain elements to shuffle.
  while (currentIndex != 0) {
    // Pick a remaining element.
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    // And swap it with the current element.
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex],
      array[currentIndex],
    ];
  }

  return array;
}

//To implement this I had to console log the result
//I was then wanting to use this variable to I had to console log it and paste it in
//I found this command on the internet to let node display entire array
// const util = require("util");
// console.log(
//   util.inspect(shuffle(possibleWordsArrayAlphabetical), {
//     maxArrayLength: null,
//   })
// );

//the final shuffled array to use for the wordle function
const possibleWordsArray = [
  "TOXIC",
  "BEADY",
  "RANGE",
  "GLASS",
  "HAPPY",
  "CACAO",
  "ABBEY",
  "THERE",
  "STAND",
  "ROBIN",
  "ALTAR",
  "CRANE",
  "YOUTH",
  "EQUAL",
  "STAGE",
  "QUERY",
  "COCOA",
  "CHAFE",
  "BALSA",
  "APPLY",
  "SALSA",
  "SCARE",
  "COMMA",
  "DOWRY",
  "PAPER",
  "CRUST",
  "SAINT",
  "AVAIL",
  "PERKY",
  "DWELT",
  "NAIVE",
  "SIEGE",
  "LEMON",
  "OLIVE",
  "BELCH",
  "PRIME",
  "DEPTH",
  "QUART",
  "THIRD",
  "PULPY",
  "HYPER",
  "AGREE",
  "STAID",
  "ROYAL",
  "MAIZE",
  "VIRAL",
  "HUMID",
  "UNMET",
  "OUTDO",
  "PLUNK",
  "IGLOO",
  "WHOOP",
  "HEIST",
  "BREAK",
  "POKER",
  "FLESH",
  "SEDAN",
  "WROTE",
  "TWANG",
  "YEARN",
  "HATCH",
  "FORGE",
  "UNZIP",
  "WASTE",
  "CRAZE",
  "BLURB",
  "MOIST",
  "LIVER",
  "PROVE",
  "FLOOD",
  "SCOLD",
  "RUDDY",
  "CHOKE",
  "GUILD",
  "SHYLY",
  "BELLY",
  "DEATH",
  "APPLE",
  "MODEL",
  "RUDER",
  "GROWL",
  "EGRET",
  "GROVE",
  "PINEY",
  "MATEY",
  "TOTEM",
  "LOFTY",
  "EXCEL",
  "MAPLE",
  "TEPID",
  "EXULT",
  "ELDER",
  "ALLOW",
  "SOLAR",
  "ULCER",
  "NAVAL",
  "LUSTY",
  "PICKY",
  "CHILL",
  "UNFED",
  "CHARM",
  "CIVIC",
  "BLUFF",
  "HOMER",
  "HURRY",
  "FINER",
  "THYME",
  "GUPPY",
  "COULD",
  "SHAME",
  "SWEEP",
  "STORE",
  "ABACK",
  "LOOPY",
  "HUMAN",
  "TEASE",
  "SONIC",
  "KAZOO",
  "USAGE",
  "HOUND",
  "FROTH",
  "HORSE",
  "ISLET",
  "VAGUE",
  "PARRY",
  "LAPSE",
  "BLACK",
  "DELVE",
  "GROIN",
  "DRINK",
  "FOGGY",
  "UTTER",
  "EJECT",
  "RHYME",
  "SLOTH",
  "NATAL",
  "PANEL",
  "ADOPT",
  "ITCHY",
  "SNARL",
  "GLEAN",
  "SLATE",
  "LAPEL",
  "ALOFT",
  "MOUSE",
  "ASSET",
  "BRASH",
  "MUCKY",
  "WORSE",
  "CHANT",
  "CACHE",
  "GRUEL",
  "NINTH",
  "LOSER",
  "MAJOR",
  "CANNY",
  "AGAPE",
  "MAYBE",
  "MUMMY",
  "SOWER",
  "TWEED",
  "FLAIL",
  "AWFUL",
  "BLOWN",
  "VIGOR",
  "TRYST",
  "COMET",
  "BRAID",
  "PHOTO",
  "USURP",
  "SNEAK",
  "USUAL",
  "SPIKE",
  "TREAT",
  "GAUZE",
  "FOCAL",
  "METRO",
  "SHIRE",
  "FOUND",
  "BAYOU",
  "CATER",
  "AHEAD",
  "ALIKE",
  "BUGGY",
  "PLATE",
  "SMASH",
  "BOOZY",
  "SHINE",
  "WATCH",
  "SCARF",
  "ALONE",
  "FIFTY",
  "ALOUD",
  "SEVER",
  "MANLY",
  "SNACK",
  "CHEAT",
  "THUMP",
  "ALIEN",
  "BROKE",
  "PLAZA",
  "KARMA",
  "FAVOR",
  "COAST",
  "WALTZ",
  "LYING",
  "CORNY",
  "LILAC",
  "AVERT",
  "LABOR",
  "CRIMP",
  "LEAVE",
  "TREND",
  "DENIM",
  "GULLY",
  "PRIMO",
  "RATIO",
  "JAZZY",
  "RHINO",
  "SPEND",
  "TIGER",
  "KNOCK",
  "SLUNG",
  "AGATE",
  "THEME",
  "ARBOR",
  "AORTA",
  "HEATH",
  "INEPT",
  "STAFF",
  "COVET",
  "DITTO",
  "BRISK",
  "DRAIN",
  "ADOBE",
  "CRAZY",
  "VALET",
  "BEEFY",
  "GLOOM",
  "SCALD",
  "BREAD",
  "BRIAR",
  "RETRO",
  "BELIE",
  "UNDER",
  "MARRY",
  "STOMP",
  "BASIC",
  "DWARF",
  "AROMA",
  "DROLL",
  "OFFAL",
  "PEACH",
  "GLOVE",
  "ADMIT",
  "CLOCK",
  "BENCH",
  "TACIT",
  "CARRY",
  "VOUCH",
  "CROAK",
  "WHACK",
  "PAUSE",
  "BRAKE",
  "DUVET",
  "NASTY",
  "SKIRT",
  "PRINT",
  "SCRAP",
  "TRUSS",
  "APRON",
  "AGLOW",
  "DANDY",
  "PANIC",
  "OTHER",
  "LOGIC",
  "UNTIE",
  "DREAM",
  "MIMIC",
  "SHAKE",
  "CRAMP",
  "CLERK",
  "FLOAT",
  "CHIEF",
  "TAPIR",
  "DANCE",
  "BOOZE",
  "SWIRL",
  "TORSO",
  "TRICE",
  "SWEAT",
  "CONIC",
  "WRONG",
  "UNIFY",
  "CINCH",
  "RENEW",
  "VOICE",
  "WHIFF",
  "RECAP",
  "DONOR",
  "CRUMB",
  "TRITE",
  "SPIEL",
  "SPICY",
  "MANOR",
  "ROOMY",
  "AUDIT",
  "PLANT",
  "ALTER",
  "USHER",
  "HUMPH",
  "FJORD",
  "SQUAD",
  "ESSAY",
  "GUARD",
  "FLOOR",
  "GLYPH",
  "WRUNG",
  "TILDE",
  "GLOAT",
  "APTLY",
  "HORDE",
  "MERIT",
  "CLASS",
  "FOCUS",
  "OXIDE",
  "TRASH",
  "VALID",
  "PRIDE",
  "POISE",
  "YIELD",
  "WOVEN",
  "SNAFU",
  "KAYAK",
  "POINT",
  "BRING",
  "SHARD",
  "STINK",
  "GRIPE",
  "PINKY",
  "SKILL",
  "LINEN",
  "CLOTH",
  "HELIX",
  "MOUNT",
  "USING",
  "ROGUE",
  "TWICE",
  "HERON",
  "LUNAR",
  "BADGE",
  "INTER",
  "FLOSS",
  "DOUBT",
  "TWINE",
  "GHOUL",
  "SNOUT",
  "ARGUE",
  "ROUND",
  "AGILE",
  "FRONT",
  "GROUP",
  "FLORA",
  "LIBEL",
  "ENJOY",
  "FORGO",
  "AGONY",
  "MIDGE",
  "ENEMA",
  "FLUFF",
  "UNLIT",
  "FUNGI",
  "CONDO",
  "WHELP",
  "FLAIR",
  "TRAIN",
  "GRIME",
  "MADAM",
  "COUNT",
  "TRAWL",
  "CROSS",
  "UPSET",
  "NEEDY",
  "DEBUG",
  "NYMPH",
  "MARSH",
  "UNDUE",
  "JAUNT",
  "KHAKI",
  "YACHT",
  "RADIO",
  "SMITE",
  "CHARD",
  "FERRY",
  "GIRTH",
  "EPOXY",
  "FIXER",
  "OUGHT",
  "MAGIC",
  "CATCH",
  "LARVA",
  "SURLY",
  "ULTRA",
  "BATON",
  "PILOT",
  "BRIBE",
  "TASTY",
  "EXIST",
  "STUDY",
  "STEAD",
  "VOTER",
  "TIPSY",
  "FROST",
  "AWAKE",
  "TROLL",
  "CIRCA",
  "SHRUG",
  "THORN",
  "TASTE",
  "RANCH",
  "LEDGE",
  "BRAVE",
  "BATTY",
  "SPIRE",
  "ACUTE",
  "IONIC",
  "JOKER",
  "ATOLL",
  "ABATE",
  "CEDAR",
  "RAMEN",
  "CRASS",
  "FORAY",
  "BIOME",
  "RIVAL",
  "METAL",
  "SMEAR",
  "THEIR",
  "MONTH",
  "KNOLL",
  "LABEL",
  "ROUGE",
  "MOULT",
  "DRIVE",
  "REACT",
  "CAULK",
  "HAIRY",
  "SERVE",
  "DOZEN",
  "GAMER",
  "MONEY",
  "GUANO",
  "PLUCK",
  "STING",
  "ELOPE",
  "CHAMP",
  "SKIMP",
  "PRICK",
  "CARGO",
  "INPUT",
  "MOOSE",
  "REPAY",
  "THIEF",
  "GROUT",
  "KEBAB",
  "COLON",
  "IRONY",
  "DELTA",
  "LATTE",
  "GRATE",
  "ALPHA",
  "MAXIM",
  "STALE",
  "EVERY",
  "LEAFY",
  "FLIRT",
  "SHIRK",
  "GAWKY",
  "GAMMA",
  "LAYER",
  "HATER",
  "BOOST",
  "ENNUI",
  "BLURT",
  "MASSE",
  "POLKA",
  "INANE",
  "FROCK",
  "SLUMP",
  "BIRTH",
  "CHUTE",
  "PLEAT",
  "PURGE",
  "PHASE",
  "SMART",
  "SQUAT",
  "FLOCK",
  "SHOWN",
  "TRIAD",
  "BRINE",
  "ELUDE",
  "MEDAL",
  "SOGGY",
  "CRANK",
  "CREAK",
  "KOALA",
  "BOOBY",
  "START",
  "CLING",
  "BESET",
  "POUND",
  "SUGAR",
  "MARCH",
  "TIARA",
  "CIDER",
  "FOYER",
  "TANGY",
  "BELOW",
  "FRAME",
  "PARER",
  "MOURN",
  "GIANT",
  "HOARD",
  "FLICK",
  "EMAIL",
  "TRAIT",
  "CLEAN",
  "THUMB",
  "CREDO",
  "LOWLY",
  "LEAPT",
  "SLEEK",
  "PLANK",
  "ERODE",
  "LOCUS",
  "SOLVE",
  "GREAT",
  "WHINE",
  "ANGRY",
  "ACRID",
  "PERCH",
  "ABOVE",
  "STICK",
  "GOOSE",
  "ANGER",
  "ABYSS",
  "ATONE",
  "TAUNT",
  "VITAL",
  "WACKY",
  "AMBER",
  "BADLY",
  "BANAL",
  "FARCE",
  "SCOUT",
  "FEIGN",
  "FISHY",
  "SHRUB",
  "ASIDE",
  "GOUGE",
  "REBUS",
  "MOTTO",
  "IMPEL",
  "RIPER",
  "FLASK",
  "WINCE",
  "PIETY",
  "PROBE",
  "ERROR",
  "TROVE",
  "AMPLE",
  "ADORE",
  "BORAX",
  "QUIET",
  "BEAST",
  "MINCE",
  "GAUDY",
  "GECKO",
  "TROPE",
  "CHUNK",
  "SOUND",
  "CRAVE",
  "SURER",
  "SCORN",
  "RUPEE",
  "TOUGH",
  "CHEST",
  "PIXIE",
  "SULKY",
  "TAPER",
  "CLOWN",
  "CLICK",
  "CRIME",
  "MOLAR",
  "SLOSH",
  "FIRST",
  "SWINE",
  "ZESTY",
  "COYLY",
  "LIGHT",
  "MEALY",
  "FLUME",
  "FEAST",
  "UNFIT",
  "HEADY",
  "STAIR",
  "BAGEL",
  "UNITE",
  "BEGIN",
  "FLING",
  "DIGIT",
  "FIELD",
  "GOLEM",
  "STOCK",
  "JUDGE",
  "SAUTE",
  "HUTCH",
  "WOKEN",
  "DODGE",
  "SALAD",
  "HOWDY",
  "BLUSH",
  "EVADE",
  "CHEEK",
  "SWEET",
  "GORGE",
  "TODAY",
  "WHERE",
  "SMELT",
  "SPELL",
  "REVEL",
  "BEING",
  "BERTH",
  "BLOKE",
  "FEWER",
  "STOVE",
  "APHID",
  "FAULT",
  "GRADE",
  "CREPT",
  "BROOM",
  "WEARY",
  "BAKER",
  "HAVOC",
  "IVORY",
  "MOVIE",
  "EXTRA",
  "INERT",
  "NANNY",
  "GREET",
  "GLORY",
  "CHORD",
  "PATTY",
  "STRAP",
  "PROXY",
  "OPERA",
  "SYRUP",
  "WORLD",
  "KNEEL",
  "LEERY",
  "ALBUM",
  "SHAWL",
  "CARAT",
  "BLAME",
  "WOOER",
  "SPOKE",
  "TRACE",
  "SWILL",
  "WEDGE",
  "ONSET",
  "REBUT",
  "TIBIA",
  "ETHIC",
  "FRESH",
  "ABASE",
  "SPILL",
  "STEED",
  "WORRY",
  "QUIRK",
  "CIGAR",
  "BLAND",
  "RETCH",
  "DEPOT",
  "POWER",
  "SPADE",
  "EPOCH",
  "SHALL",
  "RAINY",
  "BRINK",
  "STORY",
  "ASKEW",
  "PINTO",
  "STOOL",
  "DUTCH",
  "STOUT",
  "FORTH",
  "THOSE",
  "MOTOR",
  "GRIEF",
  "ANTIC",
  "HINGE",
  "CANOE",
  "SEEDY",
  "KIOSK",
  "SCOUR",
  "INFER",
  "SISSY",
  "SHOWY",
  "BOUGH",
  "DUCHY",
  "VIVID",
  "AGAIN",
  "QUALM",
  "REGAL",
  "AXIOM",
  "VODKA",
  "GONER",
  "NIGHT",
  "CLUCK",
  "BLEED",
  "CYNIC",
  "GRIMY",
  "PRIZE",
  "PITHY",
  "SHORN",
  "SPRAY",
  "JOUST",
  "CRATE",
  "ROBOT",
  "HUNKY",
  "MIDST",
  "HUMOR",
  "RUSTY",
  "STEIN",
  "FLOUT",
];

//Checking how many answers possible
//console.log(possibleWordsArray.length);

//Wordle function!
const wordle = (guessesLeft, answerNum) => {
  let answer = possibleWordsArray[answerNum];
  let lettersUsed = [];
  let lettersNotInWord = [];
  //console.log(answer);
  return function (guess) {
    let guessHints = [];
    let guessArray = guess.split("");
    //console.log(guessArray);
    guessesLeft--;
    for (let index = 0; index < guessArray.length; index++) {
      let currentGuessLetter = guessArray[index];
      //console.log(currentGuessLetter);
      let currentAnswerLetter = answer[index];
      //console.log(currentAnswerLetter);
      if (currentGuessLetter === currentAnswerLetter.toLowerCase()) {
        guessHints.push(currentGuessLetter.toUpperCase());
        if (lettersUsed.includes(currentGuessLetter) === false) {
          lettersUsed.push(currentGuessLetter);
        }
      } else if (answer.toLowerCase().includes(currentGuessLetter)) {
        guessHints.push(currentGuessLetter.toLowerCase());
        if (lettersUsed.includes(currentGuessLetter) === false) {
          lettersUsed.push(currentGuessLetter);
        }
      } else {
        guessHints.push("?");
        if (lettersNotInWord.includes(currentGuessLetter) === false) {
          lettersNotInWord.push(currentGuessLetter);
        }
      }
    }
    if (guessHints.join("") === answer) {
      console.log(guessHints.join(" "));
      console.log("Guesses Left: " + guessesLeft);
      console.log("Letters In Word: " + lettersUsed);
      console.log("Letters Not In Word: " + lettersNotInWord);
      console.log("YOU WON!");
      return " ";
    } else if (guessesLeft === 0 && guessHints.join("") !== answer) {
      console.log(guessHints.join(" "));
      console.log("Guesses Left: " + guessesLeft);
      console.log("Letters In Word: " + lettersUsed);
      console.log("Letters Not In Word: " + lettersNotInWord);
      console.log("The answer was " + answer + "!");
      console.log("YOU LOST!");
      return " ";
    } else {
      console.log(guessHints.join(" "));
      console.log("Guesses Left: " + guessesLeft);
      console.log("Letters In Word: " + lettersUsed);
      console.log("Letters Not In Word: " + lettersNotInWord);
      return " ";
    }
  };
};

//Play!

//Rules:
//Enter any number 1 - 735
//Make sure your guess is in lowercase
//Uppercase letters mean they are in word and in the right spot
//Lowercase letters mean they are in the word but in the wrong spot
//? means the letter is not in the word
//Have fun!

let wordleGuess = wordle(6, 400);
console.log(wordleGuess("taupe"));
